/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package funceme;

import javax.swing.JTextField;

/**
 *
 * @author Miqueias
 */
public class View2 extends javax.swing.JFrame implements Observer {

   private Modelo model;
   private ControllerView2 controller2;
    
    public View2(Modelo model) {
        this.model = model;
        this.controller2 = new ControllerView2(model, this);
        model.attach(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCidade = new javax.swing.JTextField();
        btnCidade = new javax.swing.JButton();
        txtUf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtTemperatura = new javax.swing.JTextField();
        btnTemperatura = new javax.swing.JButton();
        txtTempo = new javax.swing.JTextField();
        btnTempo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCidade.setText("Nome Cidade");
        txtCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCidadeMouseClicked(evt);
            }
        });

        btnCidade.setText("Cadastrar Cidade");
        btnCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCidadeMouseClicked(evt);
            }
        });
        btnCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCidadeActionPerformed(evt);
            }
        });

        txtUf.setText("UF");
        txtUf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUfMouseClicked(evt);
            }
        });
        txtUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUfActionPerformed(evt);
            }
        });

        jButton1.setText("Cadastrar UF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtTemperatura.setText("Temperatura");
        txtTemperatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTemperaturaMouseClicked(evt);
            }
        });

        btnTemperatura.setText("Cadastrar Temperatura");
        btnTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemperaturaActionPerformed(evt);
            }
        });

        txtTempo.setText("Tempo");
        txtTempo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTempoMouseClicked(evt);
            }
        });

        btnTempo.setText("Cadastrar Tempo");
        btnTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTempo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTemperatura, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUf, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCidade))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTemperatura))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTempo)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCidadeMouseClicked
            txtCidade.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeMouseClicked

    private void txtUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUfActionPerformed

    private void txtUfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUfMouseClicked
       txtUf.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_txtUfMouseClicked

    private void txtTemperaturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTemperaturaMouseClicked
      txtTemperatura.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperaturaMouseClicked

    private void txtTempoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTempoMouseClicked
       txtTempo.setText("");       // TODO add your handling code here:
    }//GEN-LAST:event_txtTempoMouseClicked

    private void btnCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCidadeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCidadeMouseClicked

    private void btnCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCidadeActionPerformed
                this.controller2.trataEvento(evt);                    // TODO add your handling code here:
    }//GEN-LAST:event_btnCidadeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                   this.controller2.trataEvento(evt);     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemperaturaActionPerformed
                  this.controller2.trataEvento(evt); // TODO add your handling code here:
    }//GEN-LAST:event_btnTemperaturaActionPerformed

    private void btnTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempoActionPerformed
                  this.controller2.trataEvento(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_btnTempoActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCidade;
    private javax.swing.JButton btnTemperatura;
    private javax.swing.JButton btnTempo;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtTemperatura;
    private javax.swing.JTextField txtTempo;
    private javax.swing.JTextField txtUf;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void update() {
      
    }

    public JTextField getTxtCidade() {
        return txtCidade;
    }

    public void setTxtCidade(JTextField txtCidade) {
        this.txtCidade = txtCidade;
    }

    public JTextField getTxtTemperatura() {
        return txtTemperatura;
    }

    public void setTxtTemperatura(JTextField txtTemperatura) {
        this.txtTemperatura = txtTemperatura;
    }

    public JTextField getTxtTempo() {
        return txtTempo;
    }

    public void setTxtTempo(JTextField txtTempo) {
        this.txtTempo = txtTempo;
    }

    public JTextField getTxtUf() {
        return txtUf;
    }

    public void setTxtUf(JTextField txtUf) {
        this.txtUf = txtUf;
    }
    
}
